/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:Wolf:946475:
  println("Wolf - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Wolf:946475:

public void button1_click2(GButton source, GEvent event) { //_CODE_:Panda:569234:
  println("Panda - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Panda:569234:

public void button1_click3(GButton source, GEvent event) { //_CODE_:Bear:806738:
  println("Bear - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Bear:806738:

public void button1_click4(GButton source, GEvent event) { //_CODE_:Lion:338236:
  println("Lion - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Lion:338236:

public void button1_click5(GButton source, GEvent event) { //_CODE_:PolarBear:656492:
  println("PolarBear - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:PolarBear:656492:

public void button1_click6(GButton source, GEvent event) { //_CODE_:Flamingo:875345:
  println("Flamingo - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Flamingo:875345:

public void button1_click7(GButton source, GEvent event) { //_CODE_:Kamel:285584:
  println("Kamel - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Kamel:285584:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  Wolf = new GButton(this, 130, 29, 50, 50);
  Wolf.setText("Wolfs");
  Wolf.addEventHandler(this, "button1_click1");
  Panda = new GButton(this, 93, 282, 52, 50);
  Panda.setTextAlign(GAlign.MIDDLE, GAlign.MIDDLE);
  Panda.setText("Pandas");
  Panda.addEventHandler(this, "button1_click2");
  Bear = new GButton(this, 413, 127, 50, 50);
  Bear.setText("Bears");
  Bear.addEventHandler(this, "button1_click3");
  Lion = new GButton(this, 444, 452, 50, 50);
  Lion.setText("Lions");
  Lion.addEventHandler(this, "button1_click4");
  PolarBear = new GButton(this, 588, 335, 43, 50);
  PolarBear.setText("PolarBears");
  PolarBear.addEventHandler(this, "button1_click5");
  Flamingo = new GButton(this, 718, 445, 68, 50);
  Flamingo.setText("Flamingos");
  Flamingo.addEventHandler(this, "button1_click6");
  Kamel = new GButton(this, 414, 635, 57, 50);
  Kamel.setText("Kameler");
  Kamel.addEventHandler(this, "button1_click7");
}

// Variable declarations 
// autogenerated do not edit
GButton Wolf; 
GButton Panda; 
GButton Bear; 
GButton Lion; 
GButton PolarBear; 
GButton Flamingo; 
GButton Kamel; 
